// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qctvjwlaxnidprhcxodj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjdHZqd2xheG5pZHByaGN4b2RqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDg1ODMsImV4cCI6MjA3MzE4NDU4M30.b0mOM6i2Go3qOvwgQytz_4TZcY3S4vOGzE_YmR0zxZc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});